# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Juan Ignacio Fulponi
title: economist - data scientist - researcher
email: jfulponi@economicas.uba.ar

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: jfulponi
github_username:  jfulponi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jfulponi
linkedin_username: jfulponi
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: juanif__
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Twitch 
  icon: fab fa-twitch
  url: https://www.twitch.tv/juanif_/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Juan Ignacio Fulponi and I'm an economist. I have experience in data analysis, dashboarding, data viz and geospatial structures in R and Python with huge data streams. I worked in various public sector entities and in numerous private sector companies, strengthening teamwork skills and working under pressure. Recently, I have been involved in large research and consulting projects through the Inter-American Development Bank and the University of Buenos Aires.
  
  I also love to play <mark>basketball</mark> and I cook gorgeous <mark>barbecues</mark>. I live in Argentina but I am available to move immediately to another country, something that I would love to continue developing my professional career.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Mobility patterns in Latin America
        link: https://jfulponi.shinyapps.io/dashboardmovilidad/
        link_text: Dashboard link
        additional_links:
           - title: Sample of the source code
             icon: fab fa-github
             url: https://github.com/jfulponi/OMU-Latam
           #- title:  Github page for project (eg. sproogen/modern-resume-theme)
           #  icon: fab fa-github
           #  url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Data partnership between Facebook, the University of Buenos Aires and the Inter-American Development Bank.
        description: | # this will include new lines to allow paragraphs
            I started this project through a partnership with the University of Buenos Aires but we quickly realized that Facebook mobility data needed to be processed and analyzed in a more dedicated way. This is why he joined a consulting project at the IDB, working full time on the development of the dashboard and the reports for each of the cities involved. Machine learning and statistical mechanisms were used to estimate mean distances and origin and destination matrices from the raw data with R and the dashboard was created in a Shiny environment. This information is now part of CAF's Urban Mobility Observatory. I have learned many skills through this and been I'm very proud of having this in my portfolio.
      
      - layout: top-middle
        title: Drought and Flood Loss Assessment System
        link: https://jfulponi.shinyapps.io/dashboard_test/
        link_text: Dashboard link
        additional_links:
           - title: Source Code
             icon: fab fa-github
             url: https://github.com/jfulponi/dashboard_SEPSI
           #- title:  Github page for project (eg. sproogen/modern-resume-theme)
           #  icon: fab fa-github
           #  url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This project was created in conjunction with the "Socioeconomic Vulnerability Assessment" research group of the School of Economics of the University of Buenos Aires and with the support of the Massachusetts Institute of Technology (MIT).
        description: | # this will include new lines to allow paragraphs
          The model uses machine learning to predict trend production under a scenario of normal climatic variability, from which extreme deviations in yields or area losses are evaluated that are consistent with extreme climatic events, such as severe to extreme droughts and floods affecting large areas. From this point, the variables of production and harvest loss can be geolocated and an analysis dashboard of the final results can be created.
       
      - layout: top-middle
        title: [Side project] / Bondis (buses) in the Buenos Aires Metropolitan Region
        link: https://juanif.shinyapps.io/bondisamba/
        link_text: BondisAMBA dashboard
        additional_links:
           - title: BondisBot
             icon: fab fa-twitter
             url: https://twitter.com/BondisBot
           #- title:  Github page for project (eg. sproogen/modern-resume-theme)
           #  icon: fab fa-github
           #  url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           A lot of times we create some solutions for problems that not exist (yet) because we need to keep the brain in movement. 
        description: | # this will include new lines to allow paragraphs
          I love the governance of public data. I am very interested in how governments or big companies generate public information that can be processed, transformed and contextualized. In Argentina we have tons of public data but only a few "data communicators" or... data influencers? Social networks are not only for memes. I love to share [some graphs or analysis](https://twitter.com/jfulponi/status/1515451166511054850) of topics I like. For example, I have made a [Twitter bot](https://twitter.com/BondisBot) that tweets every hour the status of the bus system in Buenos Aires. The bot compiles public information from the Buenos Aires City Government and generates some interesting variables such as quantity of buses that are circulating above max speed. This data can be viewed in the Shiny dashbard too. 
   
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: INDEC - National Institute of Statistics and Censuses
        link: indec.gob.ar
        # link_text: boringcompany.com
        sub_title: Product Owner
        caption: November 2021 - April 2022
        quote: >
          Taking some processes of the Argentine public sector to the 21st century.
        description: | # this will include new lines to allow paragraphs
          Approximately twenty thousand sheets of paper were printed each month in order to compile the construction price index at the Argentine National Institute of Statistics. Until I arrived. The modernization process in which I was in charge made it possible to eliminate several unnecessary and rudimentary tasks. The forms that companies used to fill out manually are now scheduled emails. The program for uploading prices created in 1993 in the Clipper language has been replaced by a beautiful Shiny application. Everyone knows that working for the Argentine State usually has obstacles and complications, but even so, approximately 25 hours of handwork per month were replaced by 143 lines of code in R!
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: School of Transportation - University of San Martín
        caption: 2022-2023
        sub_title: MSC. in Transport Public Policy and Planning 
        quote: >
          Studying and exploring the problems of a sector with many deficits typical of a developing economy.
        description: | # this will include new lines to allow paragraphs
          At the University of San Martín I not only perform as a postgraduate student but also carry out research tasks. It is an area where I am constantly developing theoretical and practical concepts applied to the transportation area, with a strong presence of data science.
      - layout: left
        title: School of Economics - University of Buenos Aires
        caption: 2015-2021
        sub_title: Degree in Economics
        quote: >
          Thinking about the economy from a modern point of view and generating links with research, teaching and volunteering.
        description: | # this will include new lines to allow paragraphs
          Without a doubt, studying economics in Argentina is a great challenge, especially since everyone knows but no one understands. Beyond the macroeconomic theoretical developments, it is necessary to study each one of the productive sectors to understand the economy as a global system. From the middle of the degree, I made every effort to study transport economics and contribute my grain of sand, both from an academic and teaching point of view. I graduated with a general average of 8 and a thesis graded with 10. The thesis is titled <mark>"Traffic congestion in the City of Buenos Aires: an economic analysis of its causes and consequences"</mark>.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data science, research and economics some of my other interests and hobbies are:
      - [Streaming about programming and economics](https://www.youtube.com/watch?v=U1btEk_KZ00&t=3343s)
      - [Gaming](https://www.twitch.tv/videos/1417394773)
      - [Playing basketball](https://www.youtube.com/watch?v=Jo0-BwWWBXw)
      - [Drumming and music production](https://www.youtube.com/watch?v=9XsisAyBe4E)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
